default_platform(:android)

def to_boolean(str)
  str.downcase == 'true' || str == '1'
end

platform :android do
  desc "Runs all the tests"
  lane :test do

    # The gradle managed devices feature is experimental and we need to do the following workarounds:
      # 1. Executing the tests using groups of multiple managed devices causes memory issues. Therefore we execute the tests for every device configuration individually. 
      # 2. Sharding does not work reliable on API level 31+ right now. We therefore disable it for those API levels for now. https://stackoverflow.com/questions/75452923/android-gradle-managed-devices-fails-to-boot-emulator

    common_test_parameters = "-Pandroid.experimental.androidTest.useUnifiedTestPlatform=true -Dorg.gradle.jvmargs=-Xmx14000M"
    sharding_test_parameter = "-Pandroid.experimental.androidTest.numManagedDeviceShards=5"

    gradle(tasks: ["clean", "testDeviceReleaseUnitTest"])
    
    gradle(tasks: [common_test_parameters, sharding_test_parameter, "pixel2api28DeviceDebugAndroidTest", "--info"])
    gradle(tasks: [common_test_parameters, sharding_test_parameter, "pixel2api29DeviceDebugAndroidTest", "--info"])
    gradle(tasks: [common_test_parameters, sharding_test_parameter, "pixel2api30DeviceDebugAndroidTest", "--info"])
    gradle(tasks: [common_test_parameters, "pixel2api31DeviceDebugAndroidTest", "--info"])

    gradle(tasks: [common_test_parameters, sharding_test_parameter, "pixel6api28DeviceDebugAndroidTest", "--info"])
    gradle(tasks: [common_test_parameters, sharding_test_parameter, "pixel6api29DeviceDebugAndroidTest", "--info"])
    gradle(tasks: [common_test_parameters, sharding_test_parameter, "pixel6api30DeviceDebugAndroidTest", "--info"])
    gradle(tasks: [common_test_parameters, "pixel6api31DeviceDebugAndroidTest", "--info"])
  end

  desc "Run Android linter and ktlint"
  lane :lint do
    gradle(tasks: ["clean", "lintKotlinMain", "lintDeviceDebug", "lintPreviewDebug"])
  end

  desc 'Bump version'
  lane :bumpVersion do |options|
    skip_docs
    ensure_git_status_clean
    
    bumpBuildNumber = to_boolean(ENV['BUMP_BUILD_NUMBER'] || options[:bumpBuildNumber] || 'false')
    version = ENV['VERSION'] || options[:version] || ''

    puts "Bumping version with version:#{version} bumpBuildNumber:#{bumpBuildNumber}"
    
    oldTag = "#{android_get_version_name}-#{android_get_version_code}"
    unless version.empty?
      android_set_version_name(version_name: version)
    end
    if bumpBuildNumber
      increment_version_code(gradle_file_path: "app/build.gradle")
    end
    newTag = "#{android_get_version_name}-#{android_get_version_code}"

    next if oldTag == newTag

    puts "Writing new tag #{newTag} to github env: #{ENV['GITHUB_ENV']}"
    sh("echo 'GIT_TAG=#{newTag}' >> #{ENV['GITHUB_ENV']}")

    git_commit(path: "app/build.gradle", message: "Bump version to #{newTag}")
    add_git_tag(tag: newTag)
    push_to_git_remote(tags: false, push_options: ["tag #{newTag}"])
  end

  desc "Create new Playstore build and submit to Google Play Store"
  lane :release do |options|
    skip_docs
    
    if options[:stage] == 'preview' then
      previewRelease()
      next
    end

    if options[:stage] == 'production' then
      productionRelease()
      next
    end

    if options[:stage] == 'github' then
      githubRelease()
      next
    end
  end

  desc "Create new Playstore preview build and submit to Google Play Store"
  lane :previewRelease do
    skip_docs
    buildAndSubmit(flavor: 'preview', package_name: 'de.digitalService.useID.Preview')
  end

  desc "Create new Playstore production build and submit to Google Play Store"
  lane :productionRelease do
    skip_docs
    buildAndSubmit(flavor: 'device', package_name: 'de.digitalService.useID')
  end

  desc "Create new Playstore build and submit to Google Play Store"
  lane :buildAndSubmit do |options|
    skip_docs
    ensure_git_status_clean

    gradle(
      task: 'bundle',
      flavor: options[:flavor],
      build_type: 'Release',
      properties: {
        "sentryPublicKey" => ENV["SENTRY_PUBLIC_KEY"],
        "sentryProjectId" => ENV["SENTRY_PROJECT_ID"],
        "matomoHost" => ENV["MATOMO_HOST"],
        "matomoSiteId" => ENV["MATOMO_SITE_ID"],
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => "upload",
        "android.injected.signing.key.password" => ENV["UPLOAD_KEY_PASSWORD"]
      }
    )

    supply(
      track: 'internal',
      package_name: options[:package_name],
      json_key: ENV["FASTLANE_API_KEY_PATH"],
      release_status: 'draft',
      version_name: "#{android_get_version_name} (#{android_get_version_code})",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true
    )
  end

  desc "Create new GitHub release containing an APK"
  lane :githubRelease do |options|
    skip_docs
    ensure_git_status_clean

    version_code = android_get_version_code
    tag = "#{android_get_version_name}-#{version_code}"

    gradle(
      task: 'assemble',
      flavor: "device",
      build_type: 'Release',
      properties: {
        "sentryPublicKey" => ENV["SENTRY_PUBLIC_KEY"],
        "sentryProjectId" => ENV["SENTRY_PROJECT_ID"],
        "matomoHost" => ENV["MATOMO_HOST"],
        "matomoSiteId" => ENV["MATOMO_SITE_ID"],
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => "upload",
        "android.injected.signing.key.password" => ENV["UPLOAD_KEY_PASSWORD"]
      }
    )

    apk_path = Actions.lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]

    changelog_dir = "metadata/android/en-US/changelogs"
    specific_changelog_file = "#{changelog_dir}/#{version_code}.txt"

    changelog_file = File.file?(specific_changelog_file) ? specific_changelog_file : "#{changelog_dir}/default.txt"

    sh("gh release create #{tag} --draft --title #{tag} -F #{changelog_file} '#{apk_path}#BundesIdent-#{tag}.apk'")
  end
end
