default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(tasks: ["clean", "testDeviceDebugUnitTest"])
    gradle(tasks: ["connectedDeviceDebugAndroidTest", "--info"])
  end

  desc "Run Android linter and ktlint"
  lane :lint do
    gradle(tasks: ["clean", "lintKotlinMain", "lintDeviceDebug", "lintPreviewDebug"])
  end

  desc "Update version name and bump version code"
  lane :updateVersion do |options|
    skip_docs
    ensure_git_status_clean

    increment_version_code(gradle_file_path: "app/build.gradle")

    if options[:version_name]
      android_set_version_name(version_name: options[:version_name])
    end

    version_name = android_get_version_name
    version_code = android_get_version_code

    git_commit(path: "app/build.gradle", message: "Bump version to #{version_name}-#{version_code}")
    push_to_git_remote
  end

  desc "Create new Playstore build and submit to Google Play Store"
  lane :buildAndSubmitPreview do
    skip_docs
    buildAndSubmit(flavor: 'preview', package_name: 'de.bund.digitalservice.UseID.Preview')
  end

  desc "Create new Playstore build and submit to Google Play Store"
  lane :buildAndSubmitRelease do
    skip_docs
    buildAndSubmit(flavor: 'device', package_name: 'de.bund.digitalservice.UseID')
  end

  desc "Create new Playstore build and submit to Google Play Store"
  lane :buildAndSubmit do |options|
    skip_docs
    ensure_git_status_clean

    gradle(
      task: 'bundle',
      flavor: options[:flavor],
      build_type: 'Release',
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => "upload",
        "android.injected.signing.key.password" => ENV["UPLOAD_KEY_PASSWORD"]
      }
    )

    supply(
      track: 'internal',
      package_name: options[:package_name],
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_apk: true
    )
  end
end
